# Use postgres/example user/password credentials
version: '3.1'
services:
  pgAdmin:
     restart: always
     image: dpage/pgadmin4
     ports:
      - "8000:80"
     environment:
      PGADMIN_DEFAULT_EMAIL: alandaviov@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432